name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.9'  # Replace with the Python version you're using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Build documentation
        run: |
          cd docs
          make html

      - name: Upload built documentation as artifact
        uses: actions/upload-artifact@v2
        with:
          name: built-docs
          path: ./docs/build/html  # Ensure this matches your build directory


      - name: Create CNAME file
        run: echo "automata4cps.ai4cps.com" > ./docs/build/html/CNAME  # Replace with your custom domain


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html  # Path to the built HTML documentation
